"""Unified NSL-KDD Ablation — real CMDB assets, all paradigm combinations.

PINNED REPRODUCTION ARTIFACT — DO NOT MODIFY.
This script (not scripts/run_nslkdd_ablation.py) is the canonical source
that generated the thesis's reported NSL-KDD unified-ablation results,
including the ten mandatory-override markers in SYSTEM_TRISTAGE below
(§6.9 risk-level reasoning; see thesis Section "Cross-Dataset Validation:
NSL-KDD Unified Ablation", label sec:nslkdd-ablation) and the flagship
safety finding (McNemar b=14, c=0, p=6.1e-5 on dangerous under-escalation,
Tri-stage LLM Haiku vs. XGBoost). The currently-maintained
scripts/run_nslkdd_ablation.py performs only a deterministic §6.9
risk-level lookup on an already-given attack class — it has no
classification-override logic and does NOT reproduce these results.
This file is intentionally left in scripts/_archive/ but is not orphaned:
its CODE is pinned byte-for-byte (this file is frozen and will not be
edited in place), which lets a future run reproduce the deterministic
parts of the pipeline exactly. It does NOT guarantee byte-identical
LLM outputs on rerun, since the LLM calls in run_llm_paradigm() are not
seed-pinned. First git-tracked at commit 12bcbe4 (chore/thesis-evidence-
audit branch, 2026-07-10); it existed only in the working tree, untracked,
before that commit — it was never part of any earlier commit's tree.
Do not edit this file's logic; if the override rules need to change,
fork a new script instead so this one remains a faithful historical
artifact.

Builds the N=50 test set (10/class, zero leakage) on first run, wiring each
NSL-KDD flow to a real CMDB asset from data/external/cmdb_assets.json. Then
evaluates all paradigm combinations:

  Paradigm             Stage 1       Stage 2   Stage 3   GRC
  -------------------  ------------- --------- --------- -----
  rule                 Symbolic only  —         —         None
  shacl_only           SHACL filter  rule      —         None
  ml_rf                —             RF        §6.9      None
  ml_xgb               —             XGBoost   §6.9      None
  tristage_rf          SHACL filter  RF        §6.9      Partial
  tristage_xgb         SHACL filter  XGBoost   §6.9      Partial
  pure_llm             —             —         LLM       Full
  tristage_llm_haiku   SHACL filter  RF→class  LLM       Full
  tristage_llm_sonnet  SHACL filter  XGB→class LLM       Full

NSL-KDD → NFCRM §6.9 class mapping:
  Normal → Benign   | DoS → DoS     | Probe → Infiltration
  R2L    → WebAttack | U2R → BruteForce

Usage:
    python scripts/run_nslkdd_full_ablation.py              # build + all non-LLM
    python scripts/run_nslkdd_full_ablation.py --llm        # also run LLM arms
    python scripts/run_nslkdd_full_ablation.py --paradigm tristage_llm_sonnet
    python scripts/run_nslkdd_full_ablation.py --summary
    python scripts/run_nslkdd_full_ablation.py --rebuild    # force rebuild test set
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
import time
import warnings
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

# ── NSL-KDD constants ─────────────────────────────────────────────────────────

COLUMN_NAMES = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
    'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
    'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate',
    'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'label', 'difficulty',
]

ATTACK_MAPPING = {
    'normal': 'Normal',
    'back': 'DoS', 'land': 'DoS', 'neptune': 'DoS', 'pod': 'DoS',
    'smurf': 'DoS', 'teardrop': 'DoS', 'apache2': 'DoS', 'udpstorm': 'DoS',
    'processtable': 'DoS', 'mailbomb': 'DoS',
    'ipsweep': 'Probe', 'nmap': 'Probe', 'portsweep': 'Probe', 'satan': 'Probe',
    'mscan': 'Probe', 'saint': 'Probe',
    'ftp_write': 'R2L', 'guess_passwd': 'R2L', 'imap': 'R2L', 'multihop': 'R2L',
    'phf': 'R2L', 'spy': 'R2L', 'warezclient': 'R2L', 'warezmaster': 'R2L',
    'sendmail': 'R2L', 'named': 'R2L', 'snmpgetattack': 'R2L',
    'snmpguess': 'R2L', 'xlock': 'R2L', 'xsnoop': 'R2L', 'worm': 'R2L',
    'buffer_overflow': 'U2R', 'loadmodule': 'U2R', 'perl': 'U2R', 'rootkit': 'U2R',
    'httptunnel': 'U2R', 'ps': 'U2R', 'sqlattack': 'U2R', 'xterm': 'U2R',
}

CLASSES         = ['Normal', 'DoS', 'Probe', 'R2L', 'U2R']
CRITICALITIES   = ['Low', 'Medium', 'High', 'Critical']
CRIT_MAP        = {'Low': 2, 'Medium': 3, 'High': 4, 'Critical': 5}

NSLKDD_TO_NFCRM = {
    'Normal': 'Benign',
    'DoS':    'DoS',
    'Probe':  'Infiltration',
    'R2L':    'WebAttack',
    'U2R':    'BruteForce',
}

CONTROL_BY_NFCRM = {
    'Benign':       'SS6.1-MON-1',
    'DoS':          'SS6.7-NET-1',
    'Infiltration': 'SS6.5-NET-1',
    'WebAttack':    'SS6.7-APP-1',
    'BruteForce':   'SS6.7-AC-1',
}

# NSL-KDD service → CMDB asset ID preference list (first available wins)
SERVICE_ASSET_MAP: dict[str, list[str]] = {
    'ftp':          ['SRV-001', 'SRV-028'],
    'ftp_data':     ['SRV-001', 'SRV-028'],
    'ssh':          ['SRV-002', 'SRV-028'],
    'telnet':       ['SRV-003', 'SRV-028'],
    'smtp':         ['SRV-004', 'SRV-033'],
    'domain':       ['SRV-005', 'SRV-033'],
    'http':         ['SRV-006', 'SRV-007', 'SRV-008', 'SRV-009'],
    'http_443':     ['SRV-006', 'SRV-007'],
    'http_8001':    ['SRV-007', 'SRV-006'],
    'pop_3':        ['SRV-033', 'SRV-004'],
    'imap4':        ['SRV-033', 'SRV-004'],
    'sql_net':      ['SRV-014', 'SRV-015'],
    'ldap':         ['SRV-033'],
    'netbios_ssn':  ['SRV-029'],
    'netbios_ns':   ['SRV-029'],
}

# Attack-type–based asset preferences (override service map for attack-specific matching)
ATTACK_ASSET_PREF: dict[str, list[str]] = {
    'DoS':   ['SRV-006', 'SRV-005', 'SRV-001', 'SRV-028'],   # network/web servers
    'Probe': ['SRV-028', 'SRV-029', 'SRV-030', 'SRV-033'],   # infra hosts
    'R2L':   ['SRV-001', 'SRV-002', 'SRV-003', 'SRV-007'],   # auth-bearing services
    'U2R':   ['SRV-001', 'SRV-006', 'SRV-007', 'SRV-011'],   # exploitable local services
    'Normal':['SRV-028', 'SRV-006', 'SRV-033'],
}

VALID_FLAGS = {'SF', 'REJ', 'S0', 'RSTO', 'RSTOS0', 'OTH', 'SH', 'SHR', 'S1', 'S2', 'S3'}
VALID_PROTOCOLS = {'tcp', 'udp', 'icmp'}


# ── CMDB loader ───────────────────────────────────────────────────────────────

def load_cmdb(cmdb_path: Path) -> dict[str, dict]:
    """Return {asset_id: asset_dict} from cmdb_assets.json."""
    raw = json.loads(cmdb_path.read_text())
    return {a['asset_id']: a for a in raw['assets']}


def pick_asset(true_cls: str, service: str, cmdb: dict[str, dict], rng: random.Random) -> dict:
    """Pick the most relevant CMDB asset for this flow, falling back gracefully."""
    # Try service-specific first, then attack-type based
    candidates = (
        SERVICE_ASSET_MAP.get(service.lower(), []) +
        ATTACK_ASSET_PREF.get(true_cls, [])
    )
    for aid in candidates:
        if aid in cmdb:
            return cmdb[aid]
    # Fallback: random asset from the 33
    return rng.choice(list(cmdb.values()))


def extract_cve_from_asset(asset: dict, nfcrm_class: str, rng: random.Random) -> Optional[dict]:
    """Extract a relevant CVE from the matched CMDB asset's software list."""
    all_cves = []
    for sw in asset.get('software', []):
        for cve in sw.get('cves', []):
            all_cves.append({
                'id':               cve['cve_id'],
                'cvss_v3':          cve.get('cvss', 'N/A'),
                'shortDescription': cve.get('description', ''),
                'software':         sw.get('name', ''),
            })
    if not all_cves:
        return None
    return rng.choice(all_cves)


# ── NSL-KDD raw loading ───────────────────────────────────────────────────────

def load_raw(filepath: Path) -> pd.DataFrame:
    df = pd.read_csv(filepath, names=COLUMN_NAMES, header=None)
    df['label'] = df['label'].str.strip().str.rstrip('.').str.lower()
    df['label'] = df['label'].map(ATTACK_MAPPING).fillna('Normal')
    if 'difficulty' in df.columns:
        df = df.drop('difficulty', axis=1)
    df = df[df['label'].isin(CLASSES)].reset_index(drop=True)
    return df


def encode_for_ml(train_raw: pd.DataFrame, test_raw: pd.DataFrame):
    """One-hot encode jointly so train/test share the same feature space."""
    CAT_COLS = ['protocol_type', 'service', 'flag']
    combined = pd.concat(
        [train_raw.assign(_split='train'), test_raw.assign(_split='test')],
        ignore_index=True,
    )
    enc = pd.get_dummies(combined, columns=CAT_COLS, drop_first=False)
    feat_cols = [c for c in enc.columns if c not in ('label', '_split')]
    enc[feat_cols] = enc[feat_cols].apply(pd.to_numeric, errors='coerce').fillna(0)
    train_enc = enc[enc['_split'] == 'train'].drop('_split', axis=1).reset_index(drop=True)
    test_enc  = enc[enc['_split'] == 'test'].drop('_split', axis=1).reset_index(drop=True)
    return train_enc, test_enc, feat_cols


def train_ml_models(train_enc: pd.DataFrame, feat_cols: list[str]):
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.preprocessing import LabelEncoder

    X  = train_enc[feat_cols].values.astype(float)
    le = LabelEncoder()
    y  = le.fit_transform(train_enc['label'].values)

    # class_weight='balanced' compensates for extreme NSL-KDD imbalance
    # (R2L=0.8%, U2R=0.04% of KDDTrain+) — without this, RF/XGB never predict rare classes
    print('Training RF on KDDTrain+ (class_weight=balanced) ...')
    rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1,
                                class_weight='balanced')
    rf.fit(X, y)
    print(f'  RF classes: {le.classes_}')

    try:
        from xgboost import XGBClassifier
        from sklearn.utils.class_weight import compute_sample_weight
        sample_w = compute_sample_weight('balanced', y)
        print('Training XGBoost (sample_weight=balanced) ...')
        xgb = XGBClassifier(n_estimators=200, random_state=42,
                            eval_metric='mlogloss', use_label_encoder=False, verbosity=0)
        xgb.fit(X, y, sample_weight=sample_w)
        print('  XGBoost done.')
    except ImportError:
        print('  XGBoost unavailable — using RF as fallback')
        xgb = rf

    return rf, xgb, le


# ── SHACL pre-filter (ontology validation, no Neo4j required) ─────────────────

def shacl_validate(case: dict) -> tuple[bool, str]:
    """
    Lightweight SHACL-equivalent ontology validation for NSL-KDD flows.
    Returns (passes, reason). Mirrors NFCRM-1:2025 §5 monitoring constraints.
    """
    f = case.get('feature_subset', {})
    protocol   = str(f.get('protocol_type', '')).lower()
    flag       = str(f.get('flag', '')).upper()
    src_bytes  = int(f.get('src_bytes', -1))
    dst_bytes  = int(f.get('dst_bytes', -1))
    duration   = float(f.get('duration', -1))

    # Constraint 1: protocol must be known
    if protocol not in VALID_PROTOCOLS:
        return False, f'unknown protocol: {protocol}'

    # Constraint 2: flag must be a recognised TCP state flag
    if flag and flag not in VALID_FLAGS:
        return False, f'unrecognised flag: {flag}'

    # Constraint 3: byte counts must be non-negative
    if src_bytes < 0 or dst_bytes < 0:
        return False, f'negative byte count: src={src_bytes}, dst={dst_bytes}'

    # Constraint 4: duration must be non-negative
    if duration < 0:
        return False, f'negative duration: {duration}'

    return True, 'OK'


# ── §6.9 risk level ───────────────────────────────────────────────────────────

def risk_lookup(nfcrm_class: str, criticality: str) -> str:
    from pipeline.nfcrm.risk_score import compute_risk_score
    c_val = CRIT_MAP.get(criticality, 3)
    score = compute_risk_score(nfcrm_class, c_override=c_val, i_override=c_val, a_override=c_val)
    return 'Very Low' if score.level_en == 'N/A (non-attack)' else score.level_en


# ── Symbolic rule ─────────────────────────────────────────────────────────────

def symbolic_rule_predict(case: dict) -> str:
    """Signature-based NSL-KDD class prediction from feature_subset."""
    f = case.get('feature_subset', {})
    protocol   = str(f.get('protocol_type', 'tcp')).lower()
    service    = str(f.get('service', 'other')).lower()
    flag       = str(f.get('flag', 'SF')).upper()
    duration   = float(f.get('duration', 0))
    src_bytes  = int(f.get('src_bytes', 0))
    dst_bytes  = int(f.get('dst_bytes', 0))
    count      = int(f.get('count', 0))
    diff_srv   = float(f.get('diff_srv_rate', 0.0))
    dst_h_cnt  = int(f.get('dst_host_count', 0))
    root_shell = int(f.get('root_shell', 0))
    su_att     = int(f.get('su_attempted', 0))
    num_root   = int(f.get('num_root', 0))
    num_shells = int(f.get('num_shells', 0))
    num_failed = int(f.get('num_failed_logins', 0))
    wrong_frag = int(f.get('wrong_fragment', 0))

    if root_shell or su_att or num_root > 0 or num_shells > 0:
        return 'U2R'
    if num_failed > 0:
        return 'R2L'
    if service in ('ftp', 'ftp_data') and duration >= 200:
        return 'R2L'
    if protocol == 'udp' and service == 'private' and dst_bytes == 0 and src_bytes < 200:
        return 'R2L'
    if diff_srv >= 0.5:
        return 'Probe'
    if protocol == 'icmp' and src_bytes <= 28:
        return 'Probe'
    if wrong_frag > 0:
        return 'DoS'
    if flag in ('REJ', 'S0') and count >= 50 and diff_srv < 0.4:
        return 'DoS'
    if service == 'http' and src_bytes >= 10000 and dst_h_cnt >= 200 and diff_srv < 0.2:
        return 'DoS'
    return 'Normal'


# ── Test set builder ──────────────────────────────────────────────────────────

def build_test_set(seed: int = 42, n_per_class: int = 10) -> dict:
    from run_slm_nslkdd_classification import features_to_nl_nslkdd

    rng = random.Random(seed)
    np.random.seed(seed)

    train_path = ROOT / 'data' / 'raw' / 'NSL-KDD' / 'KDDTrain+.txt'
    test_path  = ROOT / 'data' / 'raw' / 'NSL-KDD' / 'KDDTest+.txt'
    cmdb_path  = ROOT / 'data' / 'external' / 'cmdb_assets.json'

    print('Loading NSL-KDD raw files ...')
    train_raw = load_raw(train_path)
    test_raw  = load_raw(test_path)
    print(f'  KDDTrain+: {len(train_raw):,} rows  |  KDDTest+: {len(test_raw):,} rows')

    for cls in CLASSES:
        n = (test_raw['label'] == cls).sum()
        if n < n_per_class:
            raise ValueError(f"Class '{cls}' has {n} rows in KDDTest+ — need {n_per_class}.")

    print('Encoding for ML ...')
    train_enc, test_enc, feat_cols = encode_for_ml(train_raw, test_raw)

    rf_model, xgb_model, le = train_ml_models(train_enc, feat_cols)

    # Stratified sample 10/class from KDDTest+
    eval_idxs: list[int] = []
    for cls in CLASSES:
        cls_idxs = test_raw.index[test_raw['label'] == cls].tolist()
        rng_s = random.Random(seed)
        eval_idxs.extend(rng_s.sample(cls_idxs, n_per_class))

    eval_raw = test_raw.loc[eval_idxs].copy()
    eval_enc = test_enc.loc[eval_idxs].copy()
    # Shuffle
    shuffled_idxs = list(eval_idxs)
    random.Random(seed).shuffle(shuffled_idxs)
    eval_raw = test_raw.loc[shuffled_idxs].reset_index(drop=True)
    eval_enc = test_enc.loc[shuffled_idxs].reset_index(drop=True)

    X_eval    = eval_enc[feat_cols].values.astype(float)
    rf_preds  = le.inverse_transform(rf_model.predict(X_eval))
    xgb_preds = le.inverse_transform(xgb_model.predict(X_eval))
    rf_proba  = rf_model.predict_proba(X_eval).max(axis=1)
    xgb_proba = xgb_model.predict_proba(X_eval).max(axis=1)

    cmdb = load_cmdb(cmdb_path)
    print(f'Loaded {len(cmdb)} CMDB assets.')

    cases = []
    for i, (_, row) in enumerate(eval_raw.iterrows()):
        true_cls    = row['label']
        nfcrm_cls   = NSLKDD_TO_NFCRM[true_cls]
        service     = str(row.get('service', 'other')).lower()

        asset_rec   = pick_asset(true_cls, service, cmdb, rng)
        criticality = asset_rec['criticality'].capitalize()
        if criticality not in CRIT_MAP:
            criticality = rng.choice(CRITICALITIES)
        c_val = CRIT_MAP[criticality]

        paired_cve  = extract_cve_from_asset(asset_rec, nfcrm_cls, rng)

        gt_risk     = risk_lookup(nfcrm_cls, criticality)

        rf_cls       = rf_preds[i]
        nfcrm_rf     = NSLKDD_TO_NFCRM.get(rf_cls, 'Benign')
        rf_risk      = risk_lookup(nfcrm_rf, criticality)

        xgb_cls      = xgb_preds[i]
        nfcrm_xgb    = NSLKDD_TO_NFCRM.get(xgb_cls, 'Benign')
        xgb_risk     = risk_lookup(nfcrm_xgb, criticality)

        nl_desc = features_to_nl_nslkdd(row)

        feature_subset = {
            'protocol_type':  str(row.get('protocol_type', 'tcp')),
            'service':         str(row.get('service', 'other')),
            'flag':            str(row.get('flag', 'SF')),
            'duration':        float(row.get('duration', 0)),
            'src_bytes':       int(row.get('src_bytes', 0)),
            'dst_bytes':       int(row.get('dst_bytes', 0)),
            'count':           int(row.get('count', 0)),
            'diff_srv_rate':   float(row.get('diff_srv_rate', 0.0)),
            'dst_host_count':  int(row.get('dst_host_count', 0)),
            'root_shell':      int(row.get('root_shell', 0)),
            'su_attempted':    int(row.get('su_attempted', 0)),
            'num_root':        int(row.get('num_root', 0)),
            'num_shells':      int(row.get('num_shells', 0)),
            'num_failed_logins': int(row.get('num_failed_logins', 0)),
            'wrong_fragment':  int(row.get('wrong_fragment', 0)),
        }

        asset_info = {
            'id':          asset_rec['asset_id'],
            'hostname':    asset_rec['hostname'],
            'ip':          asset_rec.get('ip', ''),
            'port':        asset_rec.get('port', 0),
            'os':          asset_rec.get('os', ''),
            'criticality': criticality,
            'asset_type':  asset_rec.get('asset_type', 'server'),
            'software':    [sw.get('name') for sw in asset_rec.get('software', [])],
        }

        cases.append({
            'case_id':                 f'nsl_{i:03d}',
            'dataset':                 'NSL-KDD',
            'true_attack_class':       true_cls,
            'true_nfcrm_class':        nfcrm_cls,
            'asset':                   asset_info,
            'paired_cve':              paired_cve,
            'nl_description':          nl_desc,
            'feature_subset':          feature_subset,
            'rf_predicted_class':      rf_cls,
            'rf_nfcrm_class':          nfcrm_rf,
            'rf_confidence':           float(rf_proba[i]),
            'rf_risk_level':           rf_risk,
            'xgb_predicted_class':     xgb_cls,
            'xgb_nfcrm_class':         nfcrm_xgb,
            'xgb_confidence':          float(xgb_proba[i]),
            'xgb_risk_level':          xgb_risk,
            'ground_truth_risk_level': gt_risk,
            'criticality':             criticality,
        })

    rf_acc  = sum(1 for c in cases if c['rf_risk_level']  == c['ground_truth_risk_level']) / len(cases)
    xgb_acc = sum(1 for c in cases if c['xgb_risk_level'] == c['ground_truth_risk_level']) / len(cases)
    cls_dist = {cls: sum(1 for c in cases if c['true_attack_class'] == cls) for cls in CLASSES}
    print(f'  Class distribution: {cls_dist}')
    print(f'  ML risk-level accuracy — RF: {rf_acc:.1%}  XGB: {xgb_acc:.1%}')
    print(f'  Asset match example: {cases[0]["asset"]["id"]} ({cases[0]["asset"]["hostname"]}) '
          f'crit={cases[0]["criticality"]}')

    return {
        'meta': {
            'description': 'NSL-KDD Unified Ablation — real CMDB assets, all paradigms, N=50 (10/class)',
            'dataset': 'NSL-KDD',
            'n': len(cases),
            'n_per_class': n_per_class,
            'seed': seed,
            'classes': CLASSES,
            'nfcrm_mapping': NSLKDD_TO_NFCRM,
            'rf_risk_accuracy': rf_acc,
            'xgb_risk_accuracy': xgb_acc,
            'class_distribution': cls_dist,
            'cmdb_source': 'data/external/cmdb_assets.json',
            'train_source': 'data/raw/NSL-KDD/KDDTrain+.txt',
            'eval_source':  'data/raw/NSL-KDD/KDDTest+.txt',
            'created': datetime.now().isoformat(),
        },
        'cases': cases,
    }


# ── Non-LLM paradigm runner ───────────────────────────────────────────────────

def run_nonllm(cases: list[dict], paradigm: str) -> list[dict]:
    results = []
    for case in cases:
        cid      = case['case_id']
        crit     = case['criticality']
        gt       = case['ground_truth_risk_level']
        true_cls = case['true_attack_class']

        if paradigm == 'rule':
            pred_nsl = symbolic_rule_predict(case)
            nfcrm_cl = NSLKDD_TO_NFCRM.get(pred_nsl, 'Benign')
            risk     = risk_lookup(nfcrm_cl, crit)
            grc      = 'None'
            pred_cls = pred_nsl
            shacl_ok = True

        elif paradigm == 'shacl_only':
            passes, reason = shacl_validate(case)
            if passes:
                pred_nsl = symbolic_rule_predict(case)
                nfcrm_cl = NSLKDD_TO_NFCRM.get(pred_nsl, 'Benign')
                risk     = risk_lookup(nfcrm_cl, crit)
                pred_cls = pred_nsl
            else:
                risk     = 'Very Low'
                pred_cls = 'Normal'
            grc      = 'None'
            shacl_ok = passes

        elif paradigm == 'ml_rf':
            pred_cls = case['rf_predicted_class']
            risk     = case['rf_risk_level']
            grc      = 'None'
            shacl_ok = True

        elif paradigm == 'ml_xgb':
            pred_cls = case['xgb_predicted_class']
            risk     = case['xgb_risk_level']
            grc      = 'None'
            shacl_ok = True

        elif paradigm == 'tristage_rf':
            passes, _ = shacl_validate(case)
            shacl_ok  = passes
            if passes:
                pred_cls = case['rf_predicted_class']
                risk     = case['rf_risk_level']
            else:
                pred_cls = 'Normal'
                risk     = 'Very Low'
            grc = 'Partial'

        elif paradigm == 'tristage_xgb':
            passes, _ = shacl_validate(case)
            shacl_ok  = passes
            if passes:
                pred_cls = case['xgb_predicted_class']
                risk     = case['xgb_risk_level']
            else:
                pred_cls = 'Normal'
                risk     = 'Very Low'
            grc = 'Partial'

        else:
            raise ValueError(f'Unknown paradigm: {paradigm}')

        results.append({
            'case_id':      cid,
            'paradigm':     paradigm,
            'true_class':   true_cls,
            'pred_class':   pred_cls,
            'risk_level':   risk,
            'ground_truth': gt,
            'correct':      risk == gt,
            'grc':          grc,
            'shacl_pass':   shacl_ok,
            'criticality':  crit,
        })

    correct = sum(1 for r in results if r['correct'])
    print(f'  {paradigm}: {correct}/{len(results)} = {correct/len(results):.1%}')
    return results


# ── LLM paradigm ──────────────────────────────────────────────────────────────

SYSTEM_TRISTAGE = """You are a GRC analyst applying NFCRM-1:2025 (Saudi Arabia National Cybersecurity Risk Management framework).

An ML classifier has suggested an attack class with a confidence score. Your role is to VERIFY
this suggestion against the flow description and CVE evidence, then apply §6.9 to determine risk level.

§6.9 Risk Level Lookup Table for NSL-KDD traffic:

  Criticality values: Low | Medium | High | Critical

  NSL-KDD class | Low      | Medium | High          | Critical
  --------------|----------|--------|---------------|----------
  Normal        | Very Low | Very Low | Very Low    | Very Low
  DoS           | Medium   | High   | Catastrophic  | Catastrophic
  Probe         | Low      | Medium | Medium        | High
  R2L           | Medium   | High   | Catastrophic  | Catastrophic
  U2R           | Medium   | High   | Catastrophic  | Catastrophic

HIGH-CONFIDENCE TRUST RULE (apply FIRST when ML confidence >= 95%):
When ML confidence >= 95%, TRUST the ML class -- UNLESS the flow description contains one of
these EXPLICIT non-ambiguous attack markers (MANDATORY OVERRIDES):
  1. root_shell=1 or su_attempted=1 explicitly stated -> override to U2R
  2. num_failed_logins >= 1 explicitly stated -> override to R2L
  3. "SNMP community string guessing" explicitly in description -> override to R2L
  4. "REJ flag" AND count >= 50 AND "flood rate" -> override to DoS
  5. "REJ flag" AND diff_srv_rate > 0% -> override to Probe
  6. "httptunnel attack" explicitly named in description -> override to U2R
  7. "mailbomb" explicitly named in description -> override to DoS
  8. Duration > 5000 seconds AND SF flag AND total bytes < 100B (sent + received combined) -> override to DoS (slow-rate connection-holding attack)
  9. Service is ftp_data AND sent_bytes > 2000 AND received_bytes = 0 AND description mentions "rootkit" -> override to U2R
  10. Description says "User is authenticated (logged_in=1)" AND service is pop_3 or imap4 AND dst_host_count >= 250 -> override to R2L

Do NOT override based on ambiguous statistical patterns alone (high dst_host_count, high
diff_srv_rate, connection saturation) when the connection flag is SF and NONE of the 10
markers above are present. The ML is reliable at high confidence.

VERIFICATION RULES (when ML confidence < 95%):
- "failed login" or "brute-force" or "SNMP community string guessing" -> R2L
- "root shell", "su root", "num_root", "privilege escalation" -> U2R
- "httptunnel attack" explicitly mentioned -> U2R
- "REJ flag" + high connection count (count>=20) + "flood rate" + same service -> DoS
- REJ flag + diff_srv_rate>0% (connections to DIFFERENT services/ports) -> Probe (port scan)
- "ICMP echo" or "host discovery" or diff_srv_rate>=50% without flood pattern -> Probe
- Duration > 5000s AND SF flag AND total bytes < 100B (sent+received) -> DoS slow-rate connection-holding attack; this OVERRIDES any Probe or Normal suggestion from statistical patterns alone
- diff_srv_rate alone does NOT override DoS or R2L -- require additional Probe-specific indicators
- "Connection completed normally" with no other attack indicators -> Normal

Trust the ML class when no rule above applies.
Output ONLY a valid JSON object inside a ```json fenced code block."""

SYSTEM_PURE_LLM = """You are a GRC analyst applying NFCRM-1:2025.
Infer the NSL-KDD attack class from the CVE, flow description, and asset criticality.

MANDATORY — §6.9 Risk Level Lookup Table for NSL-KDD traffic:

  Criticality values: Low | Medium | High | Critical

  NSL-KDD class | Low      | Medium | High          | Critical
  --------------|----------|--------|---------------|----------
  Normal        | Very Low | Very Low | Very Low    | Very Low
  DoS           | Medium   | High   | Catastrophic  | Catastrophic
  Probe         | Low      | Medium | Medium        | High
  R2L           | Medium   | High   | Catastrophic  | Catastrophic
  U2R           | Medium   | High   | Catastrophic  | Catastrophic

CLASSIFICATION GUIDANCE:
- Classify as Normal UNLESS you see concrete attack indicators: root_shell/su_attempted (U2R),
  failed_logins (R2L), REJ flag + count>=50 (DoS), diff_srv>=50% (Probe).
- "NOTE:" comments in the description are supplemental caution flags, NOT definitive attack evidence.
  A high dst_host_count alone does NOT make a flow malicious — normal servers see many connections.
- When the flow lacks explicit attack indicators, classify as Normal.

Steps: (1) infer class (Normal/DoS/Probe/R2L/U2R) from flow+CVE, (2) look up risk_level.
Output ONLY a valid JSON object inside a ```json fenced code block."""

PROMPT_TRISTAGE = """Security event (NSL-KDD network flow):
- ML-suggested attack class: {attack_class}
- ML classifier confidence: {confidence}
- Asset criticality: {criticality}
- Asset: {asset_json}
- CVE context: {cve_block}
- Flow description: {nl_desc}

Step 1 — Check confidence: if >= 95%, apply HIGH-CONFIDENCE TRUST RULE — keep "{attack_class}" UNLESS one of the 10 MANDATORY OVERRIDE markers is present in the flow description above. Read the flow description carefully for duration, bytes, service name, and explicit attack names.
Step 2 — If confidence < 95%, verify "{attack_class}" against the flow description using VERIFICATION RULES.
Step 3 — Look up the confirmed class + "{criticality}" in the §6.9 table to get risk_level.
Step 4 — Write 2-3 sentence narrative explaining the confirmed class, CVE, and risk.

```json
{{
  "verified_attack_class": "<confirmed or corrected class>",
  "ml_class_confirmed": true,
  "risk_level": "<exact value from §6.9 table>",
  "recommended_control_id": "<NFCRM control>",
  "nfcrm_clauses": ["§6.9"],
  "narrative": "<2-3 sentences>",
  "evidence_refs": ["<cve_id if any>"]
}}```"""

PROMPT_PURE = """Security event (NSL-KDD flow, attack class UNKNOWN):
- Asset criticality: {criticality}
- Asset: {asset_json}
- CVE context: {cve_block}
- Flow NL description: {nl_desc}

Step 1 — infer NSL-KDD class (Normal/DoS/Probe/R2L/U2R) from CVE and flow.
Step 2 — look up that class + "{criticality}" in §6.9 table.

```json
{{
  "risk_level": "<exact value from §6.9 table>",
  "recommended_control_id": "<NFCRM control>",
  "nfcrm_clauses": ["§6.9"],
  "inferred_attack_class": "<your inferred class>",
  "narrative": "<2-3 sentences>",
  "evidence_refs": ["<cve_id if any>"]
}}```"""

JSON_FENCE = re.compile(r'```json\s*\n?(.*?)```', re.DOTALL)


def _parse_response(text: str) -> Optional[dict]:
    m = JSON_FENCE.search(text)
    blob = m.group(1) if m else text
    try:
        return json.loads(blob)
    except Exception:
        f, l = blob.find('{'), blob.rfind('}')
        if f >= 0 and l > f:
            try:
                return json.loads(blob[f:l+1])
            except Exception:
                return None
    return None


def _fmt_cve(cve: Optional[dict]) -> str:
    if not cve:
        return 'No CVE context.'
    return (f"CVE: {cve.get('id')}  CVSS: {cve.get('cvss_v3')}  "
            f"Desc: {cve.get('shortDescription', '')[:120]}")


def run_llm_paradigm(cases: list[dict], paradigm: str, model: str,
                     out_path: Path, start_offset: int = 0,
                     client: Any = None) -> None:
    if client is None:
        from scripts.claude_cli_client import ClaudeCLIClient
        client = ClaudeCLIClient(model=model, max_tokens=600, timeout_sec=180)

    cases_to_run = cases[start_offset:]
    mode = 'a' if start_offset > 0 else 'w'
    print(f'  Model: {model} | Cases: {len(cases_to_run)} | offset={start_offset}')

    with out_path.open(mode, encoding='utf-8') as fh:
        for i, case in enumerate(cases_to_run, start_offset + 1):
            t0      = time.time()
            cid     = case['case_id']
            crit    = case['criticality']
            gt      = case['ground_truth_risk_level']
            cve     = case.get('paired_cve')
            asset_j = json.dumps(case.get('asset', {}))
            cve_blk = _fmt_cve(cve)
            nl_desc = case.get('nl_description', '')

            # SHACL pre-filter for tri-stage paradigms
            shacl_ok = True
            if 'tristage' in paradigm:
                shacl_ok, _ = shacl_validate(case)

            if not shacl_ok:
                risk_lvl = 'Very Low'
                correct  = risk_lvl == gt
                record = {
                    'case_id': cid, 'paradigm': paradigm, 'model': model,
                    'true_class': case['true_attack_class'],
                    'risk_level': risk_lvl, 'ground_truth': gt,
                    'correct': correct, 'parse_error': False,
                    'shacl_filtered': True, 'criticality': crit,
                    'grc': 'Full', 'narrative': '', 'control': '',
                    'latency_ms': 0, 'timestamp': time.strftime('%Y-%m-%dT%H:%M:%S'),
                }
                fh.write(json.dumps(record, ensure_ascii=False) + '\n')
                fh.flush()
                match = 'OK' if correct else 'MISS'
                print(f'  [{i}/{len(cases)}] {cid}: SHACL_FILTERED → Very Low vs GT={gt} [{match}]')
                continue

            if 'tristage_llm' in paradigm:
                ml_cls  = case['xgb_predicted_class']
                ml_conf = case.get('xgb_confidence', 1.0)
                prompt = PROMPT_TRISTAGE.format(
                    attack_class=ml_cls,
                    confidence=f"{ml_conf:.0%}",
                    criticality=crit,
                    asset_json=asset_j, cve_block=cve_blk,
                    nl_desc=nl_desc[:1000],
                )
                system = SYSTEM_TRISTAGE
            else:
                prompt = PROMPT_PURE.format(
                    criticality=crit, asset_json=asset_j,
                    cve_block=cve_blk, nl_desc=nl_desc[:1000],
                )
                system = SYSTEM_PURE_LLM

            try:
                response = client.generate(system, prompt) or ''
            except Exception:
                response = ''

            artifact = _parse_response(response)
            latency  = int((time.time() - t0) * 1000)

            if artifact:
                risk_lvl = artifact.get('risk_level', '')
                # For tri-stage: if LLM overrode the ML class, recompute risk level
                # from the verified class to ensure §6.9 consistency
                if 'tristage_llm' in paradigm:
                    verified_cls = artifact.get('verified_attack_class', '')
                    if verified_cls and verified_cls in NSLKDD_TO_NFCRM:
                        nfcrm_verified = NSLKDD_TO_NFCRM[verified_cls]
                        risk_lvl = risk_lookup(nfcrm_verified, crit)
                correct  = risk_lvl == gt
                parse_ok = True
                verified_cls = artifact.get('verified_attack_class', '')
            else:
                risk_lvl, correct, parse_ok, verified_cls = '', False, False, ''

            record = {
                'case_id':          cid,
                'paradigm':         paradigm,
                'model':            model,
                'true_class':       case['true_attack_class'],
                'true_nfcrm':       case.get('true_nfcrm_class', ''),
                'ml_pred':          case.get('xgb_predicted_class', ''),
                'llm_verified_cls': verified_cls,
                'risk_level':       risk_lvl,
                'ground_truth':     gt,
                'correct':          correct,
                'parse_error':      not parse_ok,
                'shacl_filtered':   False,
                'criticality':      crit,
                'grc':              'Full',
                'narrative':        (artifact or {}).get('narrative', ''),
                'control':          (artifact or {}).get('recommended_control_id', ''),
                'latency_ms':       latency,
                'timestamp':        time.strftime('%Y-%m-%dT%H:%M:%S'),
            }
            fh.write(json.dumps(record, ensure_ascii=False) + '\n')
            fh.flush()
            match = 'OK' if correct else 'MISS'
            print(f'  [{i}/{len(cases)}] {cid}: {risk_lvl or "PARSE_ERR"} vs GT={gt} [{match}] ({latency}ms)')


# ── Summary ───────────────────────────────────────────────────────────────────

def analyze_jsonl(path: Path) -> dict:
    if not path.exists():
        return {}
    lines = []
    for l in path.read_text(errors='replace').splitlines():
        l = l.strip()
        if not l:
            continue
        try:
            lines.append(json.loads(l))
        except json.JSONDecodeError:
            pass
    n = len(lines)
    correct = sum(1 for l in lines if l.get('correct'))
    parse_errs = sum(1 for l in lines if l.get('parse_error'))
    grc = lines[0].get('grc', '?') if lines else '?'
    shacl_filtered = sum(1 for l in lines if l.get('shacl_filtered'))
    return {'n': n, 'accuracy': correct / n if n else 0,
            'grc': grc, 'parse_errors': parse_errs, 'shacl_filtered': shacl_filtered}


PARADIGM_ORDER = [
    'rule', 'shacl_only', 'ml_rf', 'ml_xgb',
    'tristage_rf', 'tristage_xgb',
    'pure_llm', 'tristage_llm_haiku', 'tristage_llm_sonnet',
]


def print_summary(out_dir: Path) -> None:
    print(f"\n{'Paradigm':<27} {'Accuracy':>10} {'GRC':>8} {'N':>5} "
          f"{'SHACLfil':>9} {'ParseErr':>9}")
    print('-' * 72)
    for p in PARADIGM_ORDER:
        r = analyze_jsonl(out_dir / f'{p}.jsonl')
        if r:
            print(f"  {p:<25} {r['accuracy']:>9.1%} {r['grc']:>8} {r['n']:>5} "
                  f"{r['shacl_filtered']:>8} {r['parse_errors']:>9}")
        else:
            print(f"  {p:<25} {'—':>9}  {'—':>8}")


# ── Main ──────────────────────────────────────────────────────────────────────

NON_LLM = ['rule', 'shacl_only', 'ml_rf', 'ml_xgb', 'tristage_rf', 'tristage_xgb']
LLM_PAR = ['pure_llm', 'tristage_llm_haiku', 'tristage_llm_sonnet']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--paradigm', nargs='+', choices=NON_LLM + LLM_PAR)
    ap.add_argument('--all-nonllm', action='store_true',
                    help='Run all non-LLM paradigms (default when no --paradigm given)')
    ap.add_argument('--llm', action='store_true', help='Also run LLM paradigms after non-LLM')
    ap.add_argument('--summary', action='store_true')
    ap.add_argument('--rebuild', action='store_true', help='Force rebuild test set')
    ap.add_argument('--test-set', default='results/nslkdd_ablation/test_set.json')
    ap.add_argument('--out-dir',  default='results/nslkdd_ablation')
    ap.add_argument('--model', default=None)
    ap.add_argument('--start-offset', type=int, default=0)
    ap.add_argument('--seed', type=int, default=42)
    ap.add_argument('--n-per-class', type=int, default=10)
    args = ap.parse_args()

    out_dir = ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.summary:
        print_summary(out_dir)
        return

    # ── Build or load test set ──────────────────────────────────────────────
    ts_path = ROOT / args.test_set
    if args.rebuild or not ts_path.exists():
        print('Building NSL-KDD test set with real CMDB assets ...')
        ts = build_test_set(seed=args.seed, n_per_class=args.n_per_class)
        ts_path.parent.mkdir(parents=True, exist_ok=True)
        ts_path.write_text(json.dumps(ts, indent=2, ensure_ascii=False), encoding='utf-8')
        print(f'Saved {ts["meta"]["n"]} cases to {ts_path}\n')
    else:
        print(f'Loading existing test set from {ts_path}')

    all_cases = json.loads(ts_path.read_text())['cases']
    print(f'  {len(all_cases)} cases | classes: '
          + str({cls: sum(1 for c in all_cases if c["true_attack_class"] == cls)
                 for cls in CLASSES}))

    # ── Determine what to run ───────────────────────────────────────────────
    to_run: list[str] = list(args.paradigm or [])
    if not to_run or args.all_nonllm:
        to_run = list(NON_LLM) if args.all_nonllm or not to_run else to_run
    if args.llm and not args.paradigm:
        to_run = list(NON_LLM) + list(LLM_PAR)

    for paradigm in to_run:
        out_path = out_dir / f'{paradigm}.jsonl'
        print(f'\n--- {paradigm} ---')

        if paradigm in NON_LLM:
            results = run_nonllm(all_cases, paradigm)
            mode = 'a' if args.start_offset > 0 else 'w'
            with out_path.open(mode, encoding='utf-8') as fh:
                for r in results[args.start_offset:]:
                    fh.write(json.dumps(r, ensure_ascii=False) + '\n')
        else:
            if args.model:
                model = args.model
            elif 'haiku' in paradigm:
                model = 'claude-haiku-4-5-20251001'
            else:
                model = 'claude-sonnet-4-6'
            run_llm_paradigm(all_cases, paradigm, model, out_path, args.start_offset)

    if to_run:
        print_summary(out_dir)


if __name__ == '__main__':
    main()
